// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAesQwg0Ao_e6YJ2SUvnhzoF5WDbRCN5M8',
    appId: '1:1060207418990:web:5e0d79addef8415c82107f',
    messagingSenderId: '1060207418990',
    projectId: 'safeguard-20508',
    authDomain: 'safeguard-20508.firebaseapp.com',
    storageBucket: 'safeguard-20508.appspot.com',
    measurementId: 'G-NBQWMXT52R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiQgthni-Z6xvtoRigBLs7OR-g8K7GCNc',
    appId: '1:1060207418990:android:84d231ec90c3348c82107f',
    messagingSenderId: '1060207418990',
    projectId: 'safeguard-20508',
    storageBucket: 'safeguard-20508.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCix2GthMr1TxufsHx5aj2cPwCeTrYBtlU',
    appId: '1:1060207418990:ios:c5acad188c43801a82107f',
    messagingSenderId: '1060207418990',
    projectId: 'safeguard-20508',
    storageBucket: 'safeguard-20508.appspot.com',
    androidClientId: '1060207418990-mqspnt18j13k71jojfbah25tn0iud66q.apps.googleusercontent.com',
    iosClientId: '1060207418990-oa75c1jufp8hfi1aspsnbfimupovecb6.apps.googleusercontent.com',
    iosBundleId: 'com.example.safeguard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCix2GthMr1TxufsHx5aj2cPwCeTrYBtlU',
    appId: '1:1060207418990:ios:68e508b91eef88e382107f',
    messagingSenderId: '1060207418990',
    projectId: 'safeguard-20508',
    storageBucket: 'safeguard-20508.appspot.com',
    androidClientId: '1060207418990-mqspnt18j13k71jojfbah25tn0iud66q.apps.googleusercontent.com',
    iosClientId: '1060207418990-diondccfo7b6schttjd79aalshesvokl.apps.googleusercontent.com',
    iosBundleId: 'com.example.safeguard.RunnerTests',
  );
}
